spring:
  cloud:
    gateway:
      httpclient:
        ssl:
          trust-store-type: AzureKeyVault
      routes:
        - id: greeting
          uri: https://greeting-service:80/
          predicates:
            - Path=/greeting/**
