spring:
  cloud:
    gateway:
      httpclient:
        ssl:
          useInsecureTrustManager: true
      routes:
        - id: greeting
          uri: https://greeting-service:80/
          predicates:
            - Path=/greeting/**
        - id: greeting-netty
          uri: https://greeting-service-netty:80/
          predicates:
            - Path=/greeting-netty/**
