azure:
    keyvault:
        uri: https://keyvault-ssl-1234.vault.azure.net/
spring:
  cloud:
    gateway:
      httpclient:
        ssl:
          trust-store-type: AzureKeyVault
      routes:
        - id: greeting
          uri: https://greeting-service:80/
          predicates:
            - Path=/greeting/**
        - id: netty
          uri: https://greeting-service-netty:80/
          predicates:
            - Path=/**
