spring:
  cloud:
    gateway:
      httpclient:
        ssl:
          trust-store-type: AzureKeyVault
      routes:
        - id: greeting
          uri: lb://greeting-service/
          predicates:
            - Path=/greeting/**
